# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51a81148e02187965b0b131e0810be0cdf074008d2a180b009752dc169bef9ac6c4a100fe0715355319917e82ef4e3160f71ac5afa4e4c9ae0745ecf5d681a38

test:
  secret_key_base: 7460133970118d9296643872162a25a7780ce1721bb07fc501b212f44ead1edb3a57361bcf22ad02ddd283b996060d665a29b7d4f7f0153c1f70170d08d19102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
